### PR TITLE
Adding issue templates

### PR DESCRIPTION
**Pull request by subhamgcon**
Solves #36.  A review would be really helpful!

### CODE REVIEW

**Review by cnu1812 — CHANGES_REQUESTED** [review]
add config.yml

**Comment by subhamgcon** [comment]
@cnu1812 Can you please elaborate on what should I add in a config.yml file?

**Comment by cnu1812** [comment]
Add the socials of dok community. like youtube, slack

**Review by shreemaan-abhishek — COMMENTED** [review]
LGTM. Have you tested these changes? Also, how do you test these changes? I'm interested in learning about this. Also @cnu1812 was talking about the addition of config.yaml, what significance does it hold?

**Comment by subhamgcon** [comment]
> Add the socials of dok community. like youtube, slack

Okay adding it!

**Comment by subhamgcon** [comment]
> LGTM. Have you tested these changes? Also, how do you test these changes? I'm interested in learning about this. Also @cnu1812 was talking about the addition of config.yaml, what significance does it hold?

I can answer you in slack!

**Review by AbhijithGanesh — APPROVED** [review]

**Pull request merged**
