### PR TITLE
Homepage Component-1(What is the DoKC/our aim) added

### PR DESCRIPTION
**Pull request by Aayush987**
- This is with reference to the issue:  #34 

# Checklist:

- [x]  **What is the DoKC / our aim?**  added to the homepage. 

# Screenshot:

image

### CODE REVIEW

**Comment by ShivamTyagi12345** [comment]
please be patient :) I will review and merge it ASAP Thanks

**Comment by Aayush987** [comment]
> please be patient :) I will review and merge it ASAP Thanks

No problem ,take your time.Also tell me if it needs any improvement.

**Comment by AbhijithGanesh** [comment]
@Aayush987 we'll be redoing the designs! Once we re-do that, the PR needs to be re-created! Please stay tuned.

**Comment by Aayush987** [comment]
> @Aayush987 we'll be redoing the designs! Once we re-do that, the PR needs to be re-created! Please stay tuned.

Ok.

**Comment by ShivamTyagi12345** [comment]
thanks for coming to the rescue @AbhijithGanesh :) Sure we would be happy to assign you better issues @Aayush987

**Comment by Aayush987** [comment]
> thanks for coming to the rescue @AbhijithGanesh :) Sure we would be happy to assign you better issues @Aayush987 

Yes, always ready to work on the issues.Just ping me on the issue.

**Pull request closed without merging**
